### ISSUE TITLE
Redirect support

### ISSUE THREAD

**Issue by egoist** [egoist/saber#47] opened 2019-04-05 09:24 UTC
## Motivation

Sometimes you might change the permalink of a page, e.g. move `/about` to `/about-us` but you don't want to break existing links to `/about`

## Solution

Add a new api in `saber-browser.js`:

```js
export default ({ addRedirect }) => {
  addRedirect({
    from: '/about',
    to: '/about-us'
  })
}
```

## Implementation

In dev mode, we can simply add a redirect route in vue-router's `routes` option, in production mode, we also need to generate `about/index.html` with only `<meta http-equiv="refresh" content="0;url=/about-us" />` to redirect the page on first visit.

**Comment by MarchWorks** [comment] 2019-04-09 15:19
I will try to take care of this

**Comment by MarchWorks** [comment] 2019-04-10 12:55
@egoist for the dev mode I have added
```
const addRedirect = (array)=>{
    if (process.env.NODE_ENV !== 'production') {
      router.addRoutes(array.map((rt)=> (
        { path: `${rt.from}` , redirect: `${rt.to}.html` }
        )
      ))
    }
  }

  const browserApiContext = { Vue, router, rootOptions, addRedirect }
```
just before [create-app.js#L115](https://github.com/egoist/saber/blob/34932ffd8f34864c97e14ca240255c2bbd8c998d/packages/saber/vue-renderer/app/create-app.js#L115) I don't think that it's the right thing to do I just want to get stuff to work first. the problem is that I don't know how to get this routes in the build phase specifically in [saber/vue-renderer/lib/index.js](https://github.com/egoist/saber/blob/master/packages/saber/vue-renderer/lib/index.js) if I am not mistaken I will use them to create new pages by editing [L226-L251](https://github.com/egoist/saber/blob/34932ffd8f34864c97e14ca240255c2bbd8c998d/packages/saber/vue-renderer/lib/index.js#L226-L251)

**Comment by egoist** [comment] 2019-04-10 13:34
In dev mode you don't need to get redirect routes in the build phase since it's served as a client-side only app, your code is pretty much enough.

In production mode, we can use the ssr context:

https://github.com/egoist/saber/blob/34932ffd8f34864c97e14ca240255c2bbd8c998d/packages/saber/vue-renderer/app/entry-server.js#L3

This is the only thing we need to do in production:

```js
api.redirectRoutes = new Map()

context.addRedirect = (from, options) => {
  api.redirectRoutes.set(from, options)
}
```

We leave the actual server-side redirect implementation to plugins, e.g. we can create `saber-plugin-netlify-redirect` `saber-plugin-meta-redirect` etc, they can use `api.redirectRoutes` however they want.

**Comment by MarchWorks** [comment] 2019-04-10 17:48
@egoist  so what I should do know is nothing else than adding
```
context.addRedirect = (from, options) => {
  api.redirectRoutes.set(from, options)
}
```
after
https://github.com/egoist/saber/blob/f45c4e32bbc22d7768fb6a60718cb2a55e4c3ef5/packages/saber/vue-renderer/lib/index.js#L236
then creating a plugin which will do the redirecting job?

**Comment by egoist** [comment] 2019-04-10 17:57
yeah

**Comment by MarchWorks** [comment] 2019-04-11 11:36
@egoist help please, I created a new plugin carcass
```
const ID = 'meta-redirect'

exports.name = ID

exports.apply = (api, options = {}) => {

}
```
But I don't have any idea for what I should do inside I am really sorry for the disturbance

**Comment by MarchWorks** [comment] 2019-04-11 17:02
@egoist check if this is right I used `saber-plugin-generate-feed` as a base. I have one problem I don't know how to get `from` and `to` values from `redirectRoutes`
```
const path = require('path')

const ID = 'meta-redirect'

exports.name = ID

exports.apply = (api, options = {}) => {

  const from = '/about'
  const to = '/about-us'

  api.hooks.afterGenerate.tapPromise(ID, async () => {
 
    const { log } = api
    const { fs } = api.utils

    const createPage = (to) => {
	  return `
	    <html>
	      <head>
	        <meta http-equiv="refresh" content="0;url=${to}" />
	      </head>
	      <body>
	      </body>
	    </html>
	  `
	}

    const writePage = async (fileName, to) => {
      log.info(`Generating ${fileName}`)
      await fs.outputFile(
        path.join(api.resolveCache('public'), `${fileName}/index.html`),
        createPage(to),
        'utf8'
      )
    }

    writePage(from, to)
  })
}
```

**Comment by MarchWorks** [comment] 2019-04-12 10:22
To put it simply where should I execute `context.addRedirect`?

**Comment by egoist** [comment] 2019-04-12 10:25
You can inject a function `addRedirect ` to `browserApiContext`, in browser it calls `router.addRoutes` in node it calls `context.addRedirect`.

**Comment by MarchWorks** [comment] 2019-04-15 09:08
@egoist this one should get closed sorry I should have closed it with the PR

**Closed** 2019-04-15 09:08 UTC
Labels: enhancement
